//! FFI runtime entry points — called by C++ to start a plugin.
//!
//! Two `extern "C"` functions are provided:
//! - `malbox_run_host_plugin` — starts an IPC-based host plugin runtime.
//! - `malbox_run_guest_plugin` — starts a gRPC-based guest plugin runtime.
//!
//! Both validate the ABI version, convert the C meta struct to a Rust
//! `PluginMeta`, create a `VtablePlugin`, and then delegate to the
//! appropriate SDK runtime.

use std::ffi::{CStr, c_char};

#[cfg(feature = "guest")]
use malbox_plugin_sdk::runtime::guest::GuestPluginRuntime;
#[cfg(feature = "host")]
use malbox_plugin_sdk::runtime::host::HostRuntime;
use malbox_plugin_sdk::types::{ExecutionContext, PluginMeta, PluginState, PluginType};

use crate::error::set_last_error;
use crate::ffi_callbacks::VtablePlugin;
use crate::ffi_types::MalboxGuestRuntimeConfig;
use crate::ffi_types::{
    MALBOX_ABI_VERSION, MalboxExecutionContext, MalboxPluginMeta, MalboxPluginState,
    MalboxPluginType, MalboxPluginVtable,
};

/// Convert a `*const c_char` to a `&'static str` by copying the bytes and
/// leaking the allocation.  This is intentional: plugin metadata strings are
/// expected to be static string literals from C++ and their lifetime is the
/// entire process lifetime.
///
/// Returns `Err` if the pointer is null or the string is not valid UTF-8.
unsafe fn static_str_from_ptr(ptr: *const c_char, field: &str) -> Result<&'static str, String> {
    if ptr.is_null() {
        return Err(format!("meta.{field} is null"));
    }
    let cstr = unsafe { CStr::from_ptr(ptr) };
    let s = cstr
        .to_str()
        .map_err(|e| format!("meta.{field} is not valid UTF-8: {e}"))?;
    // Leak a copy so we can return a `&'static str`.
    let owned: &'static str = Box::leak(s.to_owned().into_boxed_str());
    Ok(owned)
}

/// Convert a non-null `*const c_char` config field to a leaked `&'static str`.
///
/// Sets the last FFI error and returns `Err(())` on failure (null pointer or
/// invalid UTF-8). Intended for the non-nullable path fields in
/// [`MalboxGuestRuntimeConfig`].
unsafe fn leak_cstr_to_static(ptr: *const c_char, field: &str) -> Result<&'static str, ()> {
    let cstr = unsafe { CStr::from_ptr(ptr) };
    match cstr.to_str() {
        Ok(s) => Ok(&*Box::leak(s.to_owned().into_boxed_str())),
        Err(e) => {
            set_last_error(&format!("config.{field} is not valid UTF-8: {e}"));
            Err(())
        }
    }
}

/// Convert a C `MalboxPluginMeta` to a Rust `PluginMeta`.
///
/// # Safety
/// All non-null pointer fields in `meta` must point to valid, null-terminated
/// C strings for the duration of this call.
unsafe fn convert_meta(meta: MalboxPluginMeta) -> Result<PluginMeta, String> {
    let name = unsafe { static_str_from_ptr(meta.name, "name") }?;
    let version = unsafe { static_str_from_ptr(meta.version, "version") }?;
    let authors = unsafe { static_str_from_ptr(meta.authors, "authors") }?;

    let description = if meta.description.is_null() {
        None
    } else {
        Some(unsafe { static_str_from_ptr(meta.description, "description") }?)
    };

    let plugin_type = match meta.plugin_type {
        MalboxPluginType::Host => PluginType::Host,
        MalboxPluginType::Guest => PluginType::Guest,
    };

    let state = match meta.state {
        MalboxPluginState::Persistent => PluginState::Persistent,
        MalboxPluginState::Ephemeral => PluginState::Ephemeral,
        MalboxPluginState::Scoped => PluginState::Scoped,
    };

    let execution = match meta.execution {
        MalboxExecutionContext::Exclusive => ExecutionContext::Exclusive,
        MalboxExecutionContext::Sequential => ExecutionContext::Sequential,
        MalboxExecutionContext::Parallel => ExecutionContext::Parallel,
        MalboxExecutionContext::Unrestricted => ExecutionContext::Unrestricted,
    };

    Ok(PluginMeta {
        name,
        version,
        description,
        authors,
        plugin_type,
        state,
        execution,
    })
}

/// Start an IPC-based host plugin runtime.
///
/// This function is called by the C++ plugin's `main()` function (generated by
/// the SDK header macro).  It validates the ABI version, converts `meta` to a
/// Rust `PluginMeta`, initialises tracing, and blocks until the plugin
/// receives a shutdown signal.
///
/// Returns `0` on clean shutdown, `-1` on any error (the error message is
/// available via [`malbox_last_error`](crate::error::malbox_last_error)).
///
/// # Safety
///
/// - `vtable.plugin_ptr` and all non-null function pointers in `vtable` must
///   remain valid for the lifetime of the process.
/// - All non-null string pointer fields in `meta` must point to valid
///   null-terminated C strings for the duration of this call.
#[cfg(feature = "host")]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn malbox_run_host_plugin(
    vtable: MalboxPluginVtable,
    meta: MalboxPluginMeta,
) -> i32 {
    if vtable.abi_version != MALBOX_ABI_VERSION {
        set_last_error(&format!(
            "ABI version mismatch: expected {MALBOX_ABI_VERSION}, got {}",
            vtable.abi_version
        ));
        return -1;
    }

    let plugin_meta = match unsafe { convert_meta(meta) } {
        Ok(m) => m,
        Err(e) => {
            set_last_error(&e);
            return -1;
        }
    };

    let plugin = VtablePlugin::new(vtable);

    malbox_plugin_sdk::internal::init_tracing("info", None);

    let runtime = match HostRuntime::new(plugin, plugin_meta) {
        Ok(r) => r,
        Err(e) => {
            set_last_error(&format!("failed to create host runtime: {e}"));
            return -1;
        }
    };

    match runtime.run() {
        Ok(()) => 0,
        Err(e) => {
            set_last_error(&format!("host runtime error: {e}"));
            -1
        }
    }
}

/// Start a gRPC-based guest plugin runtime.
///
/// This function is called by the C++ plugin's `main()` function (generated by
/// the SDK header macro).  It validates the ABI version, converts `meta` to a
/// Rust `PluginMeta`, initialises tracing, and blocks until the plugin
/// receives a shutdown signal.
///
/// Returns `0` on clean shutdown, `-1` on any error (the error message is
/// available via [`malbox_last_error`](crate::error::malbox_last_error)).
///
/// # Safety
///
/// - `vtable.plugin_ptr` and all non-null function pointers in `vtable` must
///   remain valid for the lifetime of the process.
/// - All non-null string pointer fields in `meta` and `config` must point to
///   valid null-terminated C strings for the duration of this call.
#[cfg(feature = "guest")]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn malbox_run_guest_plugin(
    vtable: MalboxPluginVtable,
    meta: MalboxPluginMeta,
    config: MalboxGuestRuntimeConfig,
) -> i32 {
    if vtable.abi_version != MALBOX_ABI_VERSION {
        set_last_error(&format!(
            "ABI version mismatch: expected {MALBOX_ABI_VERSION}, got {}",
            vtable.abi_version
        ));
        return -1;
    }

    let plugin_meta = match unsafe { convert_meta(meta) } {
        Ok(m) => m,
        Err(e) => {
            set_last_error(&e);
            return -1;
        }
    };

    // Null-check all non-nullable path fields and log_filter.
    for (ptr, name) in [
        (config.sample_dir, "sample_dir"),
        (config.artifact_dir, "artifact_dir"),
        (config.stash_dir, "stash_dir"),
        (config.log_dir, "log_dir"),
        (config.log_filter, "log_filter"),
    ] {
        if ptr.is_null() {
            set_last_error(&format!("config.{name} is null"));
            return -1;
        }
    }

    // Convert each C string to a leaked `&'static str`.
    let sample_dir = match unsafe { leak_cstr_to_static(config.sample_dir, "sample_dir") } {
        Ok(s) => s,
        Err(()) => return -1,
    };
    let artifact_dir = match unsafe { leak_cstr_to_static(config.artifact_dir, "artifact_dir") } {
        Ok(s) => s,
        Err(()) => return -1,
    };
    let stash_dir = match unsafe { leak_cstr_to_static(config.stash_dir, "stash_dir") } {
        Ok(s) => s,
        Err(()) => return -1,
    };
    let log_dir = match unsafe { leak_cstr_to_static(config.log_dir, "log_dir") } {
        Ok(s) => s,
        Err(()) => return -1,
    };
    let log_filter = match unsafe { leak_cstr_to_static(config.log_filter, "log_filter") } {
        Ok(s) => s,
        Err(()) => return -1,
    };

    let plugin = VtablePlugin::new(vtable);

    let log_dir_path = std::path::PathBuf::from(log_dir);
    let _ = std::fs::create_dir_all(&log_dir_path);
    malbox_plugin_sdk::runtime::guest::sweep_log_overflow_orphans(&log_dir_path);
    let overflow_path = log_dir_path.join(format!("run-{}.overflow.jsonl", std::process::id()));

    let log_bus = std::sync::Arc::new(malbox_plugin_sdk::log::LogBus::with_overflow(
        1024,
        overflow_path,
    ));
    malbox_plugin_sdk::internal::init_tracing(log_filter, Some(std::sync::Arc::clone(&log_bus)));
    crate::ffi_log::set_global_log_bus(std::sync::Arc::clone(&log_bus));

    let rt_config = malbox_plugin_sdk::runtime::guest::GuestRuntimeConfig {
        listen_addr: std::net::SocketAddr::V4(std::net::SocketAddrV4::new(
            std::net::Ipv4Addr::UNSPECIFIED,
            config.port,
        )),
        sample_dir,
        artifact_dir,
        stash_dir,
        log_dir,
        stash_threshold_bytes: config.stash_threshold_bytes,
        stash_ttl_secs: config.stash_ttl_secs,
        log_filter,
    };

    // `plugin_meta` comes from C++ but we no longer pass it to `with_config`
    // (the SDK's `with_config` takes only plugin + config). Keep it alive to
    // ensure its `&'static str` strings aren't dropped mid-run.
    let _meta_keepalive = plugin_meta;

    let runtime = GuestPluginRuntime::with_config(plugin, rt_config).with_log_bus(log_bus);

    match runtime.run_blocking() {
        Ok(()) => 0,
        Err(e) => {
            set_last_error(&format!("guest runtime error: {e}"));
            -1
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::CString;

    fn make_meta_cstrings() -> (CString, CString, CString, CString) {
        (
            CString::new("test-plugin").unwrap(),
            CString::new("0.1.0").unwrap(),
            CString::new("Test description").unwrap(),
            CString::new("Test Author").unwrap(),
        )
    }

    // ABI version mismatch

    #[cfg(feature = "host")]
    #[test]
    fn host_plugin_returns_minus_one_on_abi_mismatch() {
        let (name, version, desc, authors) = make_meta_cstrings();
        let meta = MalboxPluginMeta {
            name: name.as_ptr(),
            version: version.as_ptr(),
            description: desc.as_ptr(),
            authors: authors.as_ptr(),
            plugin_type: MalboxPluginType::Host,
            state: MalboxPluginState::Persistent,
            execution: MalboxExecutionContext::Sequential,
        };
        let vtable = MalboxPluginVtable {
            abi_version: MALBOX_ABI_VERSION + 1, // wrong version
            ..MalboxPluginVtable::default()
        };

        let rc = unsafe { malbox_run_host_plugin(vtable, meta) };
        assert_eq!(rc, -1);

        // Verify the error message was set.
        let err = crate::error::last_error_string();
        assert!(err.is_some());
        assert!(
            err.unwrap().contains("ABI version mismatch"),
            "expected ABI version mismatch error"
        );
    }

    #[cfg(feature = "guest")]
    #[test]
    fn guest_plugin_returns_minus_one_on_abi_mismatch() {
        let (name, version, desc, authors) = make_meta_cstrings();
        let meta = MalboxPluginMeta {
            name: name.as_ptr(),
            version: version.as_ptr(),
            description: desc.as_ptr(),
            authors: authors.as_ptr(),
            plugin_type: MalboxPluginType::Guest,
            state: MalboxPluginState::Ephemeral,
            execution: MalboxExecutionContext::Parallel,
        };
        let vtable = MalboxPluginVtable {
            abi_version: 0, // wrong version
            ..MalboxPluginVtable::default()
        };

        let filter = std::ffi::CString::new("info").unwrap();
        let sample_dir = std::ffi::CString::new("/tmp/malbox/samples").unwrap();
        let artifact_dir = std::ffi::CString::new("/tmp/malbox/artifacts").unwrap();
        let stash_dir = std::ffi::CString::new("/tmp/malbox/stash").unwrap();
        let log_dir = std::ffi::CString::new("/tmp/malbox/logs").unwrap();
        let config = MalboxGuestRuntimeConfig {
            port: 50051,
            sample_dir: sample_dir.as_ptr(),
            artifact_dir: artifact_dir.as_ptr(),
            stash_dir: stash_dir.as_ptr(),
            log_dir: log_dir.as_ptr(),
            stash_threshold_bytes: 1_048_576,
            stash_ttl_secs: 120,
            log_filter: filter.as_ptr(),
        };
        let rc = unsafe { malbox_run_guest_plugin(vtable, meta, config) };
        assert_eq!(rc, -1);

        let err = crate::error::last_error_string();
        assert!(err.is_some());
        assert!(err.unwrap().contains("ABI version mismatch"));
    }

    #[cfg(feature = "guest")]
    #[test]
    fn guest_plugin_rejects_null_sample_dir() {
        let (name, version, desc, authors) = make_meta_cstrings();
        let meta = MalboxPluginMeta {
            name: name.as_ptr(),
            version: version.as_ptr(),
            description: desc.as_ptr(),
            authors: authors.as_ptr(),
            plugin_type: MalboxPluginType::Guest,
            state: MalboxPluginState::Ephemeral,
            execution: MalboxExecutionContext::Parallel,
        };
        let vtable = MalboxPluginVtable {
            abi_version: MALBOX_ABI_VERSION,
            ..MalboxPluginVtable::default()
        };
        let filter = std::ffi::CString::new("info").unwrap();
        let artifact_dir = std::ffi::CString::new("/tmp/malbox/artifacts").unwrap();
        let stash_dir = std::ffi::CString::new("/tmp/malbox/stash").unwrap();
        let log_dir = std::ffi::CString::new("/tmp/malbox/logs").unwrap();
        let config = MalboxGuestRuntimeConfig {
            port: 50051,
            sample_dir: std::ptr::null(),
            artifact_dir: artifact_dir.as_ptr(),
            stash_dir: stash_dir.as_ptr(),
            log_dir: log_dir.as_ptr(),
            stash_threshold_bytes: 1_048_576,
            stash_ttl_secs: 120,
            log_filter: filter.as_ptr(),
        };

        let rc = unsafe { malbox_run_guest_plugin(vtable, meta, config) };
        assert_eq!(rc, -1);
        let err = crate::error::last_error_string().unwrap();
        assert!(err.contains("sample_dir"));
    }

    // Null meta fields

    #[cfg(feature = "host")]
    #[test]
    fn host_plugin_returns_minus_one_on_null_name() {
        let version = CString::new("0.1.0").unwrap();
        let authors = CString::new("Author").unwrap();
        let meta = MalboxPluginMeta {
            name: std::ptr::null(), // null!
            version: version.as_ptr(),
            description: std::ptr::null(), // nullable — ok
            authors: authors.as_ptr(),
            plugin_type: MalboxPluginType::Host,
            state: MalboxPluginState::Persistent,
            execution: MalboxExecutionContext::Sequential,
        };
        let vtable = MalboxPluginVtable {
            abi_version: MALBOX_ABI_VERSION,
            ..MalboxPluginVtable::default()
        };

        let rc = unsafe { malbox_run_host_plugin(vtable, meta) };
        assert_eq!(rc, -1);

        let err = crate::error::last_error_string();
        assert!(err.is_some());
        assert!(
            err.unwrap().contains("meta.name is null"),
            "expected null name error"
        );
    }

    #[cfg(feature = "host")]
    #[test]
    fn host_plugin_returns_minus_one_on_null_version() {
        let name = CString::new("test-plugin").unwrap();
        let authors = CString::new("Author").unwrap();
        let meta = MalboxPluginMeta {
            name: name.as_ptr(),
            version: std::ptr::null(), // null!
            description: std::ptr::null(),
            authors: authors.as_ptr(),
            plugin_type: MalboxPluginType::Host,
            state: MalboxPluginState::Persistent,
            execution: MalboxExecutionContext::Sequential,
        };
        let vtable = MalboxPluginVtable {
            abi_version: MALBOX_ABI_VERSION,
            ..MalboxPluginVtable::default()
        };

        let rc = unsafe { malbox_run_host_plugin(vtable, meta) };
        assert_eq!(rc, -1);

        let err = crate::error::last_error_string();
        assert!(err.is_some());
        assert!(err.unwrap().contains("meta.version is null"));
    }

    #[cfg(feature = "host")]
    #[test]
    fn host_plugin_returns_minus_one_on_null_authors() {
        let name = CString::new("test-plugin").unwrap();
        let version = CString::new("0.1.0").unwrap();
        let meta = MalboxPluginMeta {
            name: name.as_ptr(),
            version: version.as_ptr(),
            description: std::ptr::null(),
            authors: std::ptr::null(), // null!
            plugin_type: MalboxPluginType::Host,
            state: MalboxPluginState::Persistent,
            execution: MalboxExecutionContext::Sequential,
        };
        let vtable = MalboxPluginVtable {
            abi_version: MALBOX_ABI_VERSION,
            ..MalboxPluginVtable::default()
        };

        let rc = unsafe { malbox_run_host_plugin(vtable, meta) };
        assert_eq!(rc, -1);

        let err = crate::error::last_error_string();
        assert!(err.is_some());
        assert!(err.unwrap().contains("meta.authors is null"));
    }

    // convert_meta: null description is allowed

    #[test]
    fn convert_meta_null_description_maps_to_none() {
        let name = CString::new("plugin").unwrap();
        let version = CString::new("1.0.0").unwrap();
        let authors = CString::new("Author").unwrap();
        let meta = MalboxPluginMeta {
            name: name.as_ptr(),
            version: version.as_ptr(),
            description: std::ptr::null(), // optional
            authors: authors.as_ptr(),
            plugin_type: MalboxPluginType::Host,
            state: MalboxPluginState::Scoped,
            execution: MalboxExecutionContext::Unrestricted,
        };

        let result = unsafe { convert_meta(meta) };
        assert!(result.is_ok());
        let plugin_meta = result.unwrap();
        assert!(plugin_meta.description.is_none());
        assert_eq!(plugin_meta.name, "plugin");
    }
}
