# MalboxPluginSDKTargets.cmake — generated by the Malbox build system.
# Defines the imported target MalboxPluginSDK::MalboxPluginSDK.

cmake_minimum_required(VERSION 3.20)

if(TARGET MalboxPluginSDK::MalboxPluginSDK)
    return()
endif()

# Resolve paths relative to this file (installed alongside the library).
get_filename_component(_MALBOX_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" DIRECTORY)
get_filename_component(_MALBOX_PREFIX    "${_MALBOX_CMAKE_DIR}/.."    ABSOLUTE)

add_library(MalboxPluginSDK::MalboxPluginSDK STATIC IMPORTED)

set_target_properties(MalboxPluginSDK::MalboxPluginSDK PROPERTIES
    IMPORTED_LOCATION
        "${_MALBOX_PREFIX}/lib/libmalbox_plugin_sdk_cpp.a"
    INTERFACE_INCLUDE_DIRECTORIES
        "${_MALBOX_PREFIX}/include"
    INTERFACE_COMPILE_FEATURES
        cxx_std_20
)

# ─── Platform link dependencies ───────────────────────────────────────────────
if(UNIX AND NOT APPLE)
    # Linux
    set_property(TARGET MalboxPluginSDK::MalboxPluginSDK APPEND PROPERTY
        INTERFACE_LINK_LIBRARIES
            pthread dl rt m
    )
elseif(APPLE)
    # macOS
    set_property(TARGET MalboxPluginSDK::MalboxPluginSDK APPEND PROPERTY
        INTERFACE_LINK_LIBRARIES
            "-framework Security"
            "-framework CoreFoundation"
    )
elseif(WIN32)
    # Windows — link statically so the .exe is self-contained (no libstdc++/libgcc DLLs).
    set_property(TARGET MalboxPluginSDK::MalboxPluginSDK APPEND PROPERTY
        INTERFACE_LINK_LIBRARIES
            -static ws2_32 bcrypt userenv ntdll
    )
endif()
