[package]
name = "malbox-plugin-transport"
version = "0.1.0"
edition = "2024"

[features]
default = []
grpc = ["dep:tonic", "dep:prost", "dep:tonic-prost", "dep:tokio", "dep:tokio-stream", "dep:tonic-prost-build"]
ipc = ["dep:iceoryx2", "dep:postcard", "dep:serde", "iceoryx2/tracing"]

[dependencies]
iceoryx2 = { workspace = true, optional = true }
postcard = { version = "1", features = ["alloc"], optional = true }
serde = { workspace = true, optional = true }

tonic = { version = "0.14.6", optional = true }
prost = { version = "0.14.3", optional = true }
tonic-prost = { version = "0.14.6", optional = true }
tokio = { workspace = true, optional = true }
tokio-stream = { workspace = true, optional = true }

thiserror.workspace = true

[build-dependencies]
tonic-prost-build = { version = "0.14.6", optional = true }
