[package]
name = "malbox-plugin-manifest"
version = "0.1.0"
edition = "2024"

[dependencies]
semver = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
tempfile = { workspace = true }
toml = { workspace = true }
