//! Internal traits and helpers used by generated macro code.
//!
//! This module is `#[doc(hidden)]` — plugin authors should never use it directly.
//! The proc macros in `malbox-plugin-macros` generate implementations of these
//! traits for plugin structs.

use crate::context::Context;
use crate::error::Result;
use crate::types::{HealthStatus, PluginResult, Task};
use std::collections::HashMap;

/// Trait generated by `#[malbox::on_task]`.
pub trait TaskHandler {
    fn __handle_task(&self, task: Task, ctx: &Context) -> Result<Vec<PluginResult>>;
}

/// Trait generated by `#[malbox::on_start]`.
pub trait StartHandler {
    fn __handle_start(&self, raw_config: HashMap<String, String>) -> Result<()>;
}

/// Trait generated by `#[malbox::on_stop]`.
pub trait StopHandler {
    fn __handle_stop(&self) -> Result<()>;
}

/// Trait generated by `#[malbox::health_check]`.
pub trait HealthCheckHandler {
    fn __handle_health_check(&self) -> HealthStatus;
}

/// Trait generated by `#[malbox::on_event(...)]` for daemon events.
pub trait DaemonEventHandler {
    fn __handle_daemon_event(
        &self,
        event: malbox_plugin_transport::messages::events::DaemonEvent,
        ctx: &Context,
    ) -> Result<()>;
}

/// Trait generated by `#[malbox::on_event(...)]` for task lifecycle events.
pub trait TaskEventHandler {
    fn __handle_task_lifecycle_event(
        &self,
        event: malbox_plugin_transport::messages::events::TaskEvent,
        payload: malbox_plugin_transport::messages::events::TaskEventPayload,
        ctx: &Context,
    ) -> Result<()>;
}

/// Trait generated by `#[malbox::on_event(...)]` for plugin events.
pub trait PluginEventHandler {
    fn __handle_plugin_event(
        &self,
        event: malbox_plugin_transport::messages::events::PluginEvent,
        payload: malbox_plugin_transport::messages::events::PluginEventPayload,
        ctx: &Context,
    ) -> Result<()>;
}

/// Trait generated by `#[malbox::on_event(...)]` for sample events.
pub trait SampleEventHandler {
    fn __handle_sample_event(
        &self,
        event: malbox_plugin_transport::messages::events::SampleEvent,
        payload: malbox_plugin_transport::messages::events::SampleEventPayload,
        ctx: &Context,
    ) -> Result<()>;
}

/// Deserialize a config HashMap into a typed struct.
///
/// Used by generated `StartHandler` impls when the user's `on_start`
/// method takes a typed config parameter.
pub fn deserialize_config<T: serde::de::DeserializeOwned>(
    raw: HashMap<String, String>,
) -> Result<T> {
    let value = serde_json::to_value(raw).map_err(crate::error::SdkError::Serialization)?;
    serde_json::from_value(value).map_err(crate::error::SdkError::Serialization)
}

/// Initialize tracing with sensible defaults for plugins.
pub fn init_tracing() {
    // Use MALBOX_LOG env var, fallback to "info"
    let filter = std::env::var("MALBOX_LOG").unwrap_or_else(|_| "info".to_string());
    let subscriber = tracing_subscriber::fmt().with_env_filter(filter).finish();
    let _ = tracing::subscriber::set_global_default(subscriber);
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde::Deserialize;

    #[derive(Debug, Deserialize, PartialEq)]
    struct TestConfig {
        name: String,
        count: String, // HashMap<String,String> values are always strings
    }

    #[test]
    fn deserialize_config_works_with_valid_map() {
        let mut raw = HashMap::new();
        raw.insert("name".to_string(), "test".to_string());
        raw.insert("count".to_string(), "42".to_string());

        let config: TestConfig = deserialize_config(raw).unwrap();
        assert_eq!(config.name, "test");
        assert_eq!(config.count, "42");
    }

    #[test]
    fn deserialize_config_fails_on_missing_field() {
        let mut raw = HashMap::new();
        raw.insert("name".to_string(), "test".to_string());
        // missing "count"

        let result: Result<TestConfig> = deserialize_config(raw);
        assert!(result.is_err());
    }
}
