[package]
name = "malbox-installer"
version = "0.1.0"
edition = "2024"

[dependencies]
malbox-config = { path = "../malbox-config" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
reqwest = { workspace = true }
semver = { workspace = true }
chrono = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
dirs = "6"
flate2 = "1"
tar = "0.4"
tempfile = { workspace = true }
