//! Daemon Cargo features available to the install wizard, upgrades and
//! provider commands.
//!
//! `DAEMON_FEATURES` is generated by `build.rs` from `bin/malboxd/Cargo.toml`
//! so the feature list stays in sync with Cargo automatically. Adding a
//! `provider-*` or `provisioner-*` feature there is all that is needed for
//! it to appear in the installer prompts.

/// Whether a feature adds a virtualization provider or a machine provisioner.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FeatureKind {
    Provider,
    Provisioner,
}

/// A daemon Cargo feature exposed to users.
pub struct DaemonFeature {
    /// Human-readable label shown in interactive prompts (prefix stripped).
    pub display: &'static str,
    /// Cargo feature name as declared in `bin/malboxd/Cargo.toml`.
    pub feature: &'static str,
    /// Part of the default set (mirrors the Cargo `default` feature list).
    pub default: bool,
    /// Provider or provisioner.
    pub kind: FeatureKind,
}

include!(concat!(env!("OUT_DIR"), "/daemon_features.rs"));

/// Features in the given category.
pub fn by_kind(kind: FeatureKind) -> impl Iterator<Item = &'static DaemonFeature> {
    DAEMON_FEATURES.iter().filter(move |f| f.kind == kind)
}

/// Cargo features baked into the prebuilt `malboxd` release binaries
/// (the release workflow builds with default features).
pub fn default_features() -> Vec<String> {
    DAEMON_FEATURES
        .iter()
        .filter(|f| f.default)
        .map(|f| f.feature.to_string())
        .collect()
}

/// Cargo feature for a provider name (`"libvirt"` -> `"provider-libvirt"`),
/// or `None` when no such provider feature exists.
pub fn provider_feature(name: &str) -> Option<&'static str> {
    DAEMON_FEATURES
        .iter()
        .map(|f| f.feature)
        .find(|feature| feature.strip_prefix("provider-") == Some(name))
}

/// Provider names recognized by the build, for error messages.
pub fn known_providers() -> impl Iterator<Item = &'static str> {
    DAEMON_FEATURES
        .iter()
        .filter_map(|f| f.feature.strip_prefix("provider-"))
}

/// Split a feature set into `(providers, provisioners)` by prefix.
pub fn split_features(features: &[String]) -> (Vec<String>, Vec<String>) {
    (
        strip_prefixed(features, "provider-"),
        strip_prefixed(features, "provisioner-"),
    )
}

fn strip_prefixed(features: &[String], prefix: &str) -> Vec<String> {
    features
        .iter()
        .filter_map(|feature| feature.strip_prefix(prefix))
        .map(str::to_string)
        .collect()
}
