[package]
name = "malbox-storage"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde-inline-default = { workspace = true }
directories = "6.0.0"
tracing = { workspace = true }
tempfile = "3.10.1"
