[package]
name = "malbox-plugin-sdk"
version = "0.1.0"
edition = "2024"
description = "SDK for building Malbox analysis plugins"

[features]
host = ["malbox-plugin-transport/ipc"]
guest = []
testkit = []

[dependencies]
malbox-plugin-transport = { path = "../malbox-plugin-transport" }
malbox-plugin-macros = { path = "../malbox-plugin-macros" }

serde = { workspace = true }
serde_json = { workspace = true }
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter", "registry"] }

#iceoryx2 = { version = "0.8.1", default-features = false, optional = true }
tokio = { workspace = true }
tonic = { version = "0.14" }
prost = "0.14"
async-stream = "0.3"
tokio-stream = { workspace = true }
uuid = { workspace = true }
globset = "0.4"

[dev-dependencies]
malbox-tracing = { path = "../malbox-tracing" }
tempfile = "3.26"
futures = { workspace = true }
