[package]
name = "malbox-plugin-sdk"
version = "0.1.0"
edition = "2024"
description = "SDK for building Malbox analysis plugins"

[features]
host = []
guest = ["dep:tokio", "dep:tonic"]

[dependencies]
malbox-plugin-transport = { path = "../malbox-plugin-transport" }
malbox-plugin-macros = { path = "../malbox-plugin-macros" }

serde = { workspace = true }
serde_json = { workspace = true }
anyhow = "1"
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

#iceoryx2 = { version = "0.8.1", default-features = false, optional = true }
tokio = { workspace = true, optional = true }
tonic = { version = "0.14", optional = true }

[dev-dependencies]
malbox-tracing = { path = "../malbox-tracing" }
tempfile = "3.26"
