from pathlib import Path
from typing import Any

class TaskInfo:
    @property
    def id(self) -> int: ...
    @property
    def sample_path(self) -> Path: ...
    @property
    def config(self) -> dict[str, str]: ...
    def sample_bytes(self) -> bytes: ...
    def config_value(self, key: str) -> str | None: ...

class ResultSink:
    def push(self, result: PluginResult) -> None: ...
    def push_json(self, name: str, data: bytes) -> None: ...
    def push_bytes(self, name: str, data: bytes) -> None: ...
    def push_file(self, name: str, path: str | Path) -> None: ...
    def push_all(self, results: list[PluginResult]) -> None: ...

class Context:
    def task(self) -> TaskInfo: ...
    def results(self) -> ResultSink: ...
    def progress(self, pct: float, message: str) -> None: ...
    def emit_event(self, event: Event) -> None: ...
    def warn(self, message: str) -> None: ...
    def mark_collected(self, path: str | Path) -> None: ...

class Event:
    @property
    def kind(self) -> str: ...
    @property
    def id(self) -> int | None: ...
    @property
    def source(self) -> str | None: ...
    @property
    def result_name(self) -> str | None: ...
    @staticmethod
    def task_created(task_id: int) -> Event: ...
    @staticmethod
    def task_starting(task_id: int) -> Event: ...
    @staticmethod
    def task_completed(task_id: int) -> Event: ...
    @staticmethod
    def task_failed(task_id: int) -> Event: ...
    @staticmethod
    def task_canceled(task_id: int) -> Event: ...
    @staticmethod
    def plugin_started(plugin_id: int) -> Event: ...
    @staticmethod
    def plugin_stopped(plugin_id: int) -> Event: ...
    @staticmethod
    def plugin_result_available(source: str, result_name: str) -> Event: ...
    @staticmethod
    def sample_started(sample_id: int) -> Event: ...
    @staticmethod
    def sample_stopped(sample_id: int) -> Event: ...
    @staticmethod
    def sample_result_produced(sample_id: int) -> Event: ...
    @staticmethod
    def daemon_shutdown() -> Event: ...
    @staticmethod
    def config_reloaded() -> Event: ...

class HealthStatus:
    @property
    def is_ready(self) -> bool: ...
    @property
    def reason(self) -> str: ...
    @staticmethod
    def Healthy() -> HealthStatus: ...
    @staticmethod
    def Degraded(reason: str) -> HealthStatus: ...
    @staticmethod
    def Unhealthy(reason: str) -> HealthStatus: ...

class PluginResult:
    @property
    def name(self) -> str: ...
    @staticmethod
    def json(name: str, data: Any) -> PluginResult: ...
    @staticmethod
    def bytes(name: str, data: bytes) -> PluginResult: ...
    @staticmethod
    def file(name: str, path: str | Path) -> PluginResult: ...

class Classification:
    Clean: Classification
    Suspicious: Classification
    Malicious: Classification
    Unknown: Classification

class Confidence:
    Low: Confidence
    Medium: Confidence
    High: Confidence

class Indicator:
    def __init__(
        self,
        kind: str,
        value: str,
        context: str | None = None,
        first_seen: str | None = None,
    ) -> None: ...
    @property
    def kind(self) -> str: ...
    @property
    def value(self) -> str: ...
    @property
    def context(self) -> str | None: ...
    @property
    def first_seen(self) -> str | None: ...

class Ttp:
    def __init__(self, id: str, name: str, evidence: str | None = None) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def evidence(self) -> str | None: ...

class ArtifactRef:
    def __init__(
        self, result_name: str, kind: str, description: str | None = None
    ) -> None: ...
    @property
    def result_name(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def description(self) -> str | None: ...

class KvPair:
    def __init__(self, key: str, value: str, mono: bool = False) -> None: ...
    @property
    def key(self) -> str: ...
    @property
    def value(self) -> str: ...
    @property
    def mono(self) -> bool: ...

class Column:
    def __init__(self, key: str, label: str, type: str = "string") -> None: ...
    @property
    def key(self) -> str: ...
    @property
    def label(self) -> str: ...
    @property
    def col_type(self) -> str: ...

class Block:
    @staticmethod
    def markdown(text: str) -> Block: ...
    @staticmethod
    def callout(level: str, text: str) -> Block: ...
    @staticmethod
    def heading(level: int, text: str) -> Block: ...
    @staticmethod
    def divider() -> Block: ...
    @staticmethod
    def kv(pairs: list[KvPair]) -> Block: ...
    @staticmethod
    def table(
        columns: list[Column],
        rows: list[dict[str, Any]],
        sortable: bool = False,
        searchable: bool = False,
    ) -> Block: ...
    @staticmethod
    def code(language: str, text: str) -> Block: ...
    @staticmethod
    def json(data: Any, collapsed: bool = False) -> Block: ...
    @staticmethod
    def hex(bytes_b64: str, offset: int) -> Block: ...
    @staticmethod
    def image(artifact: str, caption: str | None = None) -> Block: ...
    @staticmethod
    def download(artifact: str, label: str) -> Block: ...
    @staticmethod
    def iocs(items: list[Indicator]) -> Block: ...
    @staticmethod
    def ttps(items: list[Ttp]) -> Block: ...
    @staticmethod
    def tree(nodes: list[TreeNode]) -> Block: ...
    @staticmethod
    def timeline(events: list[TimelineEvent]) -> Block: ...
    @staticmethod
    def graph(nodes: list[GraphNode], edges: list[GraphEdge]) -> Block: ...

class TreeNode:
    def __init__(
        self, label: str, children: list[TreeNode] | None = None, meta: Any = None
    ) -> None: ...
    @property
    def label(self) -> str: ...

class TimelineEvent:
    def __init__(
        self,
        ts: str,
        label: str,
        severity: str | None = None,
        meta: Any = None,
    ) -> None: ...
    @property
    def ts(self) -> str: ...
    @property
    def label(self) -> str: ...
    @property
    def severity(self) -> str | None: ...

class GraphNode:
    def __init__(self, id: str, label: str, meta: Any = None) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def label(self) -> str: ...

class GraphEdge:
    def __init__(
        self, from_node: str, to_node: str, label: str | None = None
    ) -> None: ...
    @property
    def from_node(self) -> str: ...
    @property
    def to_node(self) -> str: ...
    @property
    def label(self) -> str | None: ...

class ReportBuilder:
    def __init__(self, plugin_id: str, plugin_version: str) -> None: ...
    def display_name(self, name: str) -> ReportBuilder: ...
    def summary(self, summary: str) -> ReportBuilder: ...
    def verdict(
        self,
        classification: Classification,
        score: int | None = None,
        confidence: Confidence | None = None,
    ) -> ReportBuilder: ...
    def labels(self, labels: list[str]) -> ReportBuilder: ...
    def indicator(self, indicator: Indicator) -> ReportBuilder: ...
    def ttp(self, ttp: Ttp) -> ReportBuilder: ...
    def artifact(self, artifact: ArtifactRef) -> ReportBuilder: ...
    def section(self, id: str, title: str, blocks: list[Block]) -> ReportBuilder: ...
    def raw(self, value: Any) -> ReportBuilder: ...
    def build(self) -> PluginResult: ...

class SectionBuilder:
    def __init__(self) -> None: ...
    def block(self, block: Block) -> SectionBuilder: ...
    def get_blocks(self) -> list[Block]: ...

class Plugin:
    def __init__(self) -> None: ...
    def on_task(self, ctx: Context) -> None: ...
    def on_start(self, config: dict[str, str]) -> None: ...
    def on_stop(self) -> None: ...
    def health_check(self) -> HealthStatus: ...
    def on_event(self, event: Event) -> None: ...

def run(
    plugin: Plugin,
    name: str | None = None,
    version: str | None = None,
) -> None: ...

def trace(message: str) -> None: ...
def debug(message: str) -> None: ...
def info(message: str) -> None: ...
def warn(message: str) -> None: ...
def error(message: str) -> None: ...
