[workspace]
resolver = "3"
members = [
    "bin/*",
    "crates/*",
]
exclude = [
    "examples/plugins/host-file-info",
    "examples/plugins/guest-yara-scanner",
    "examples/plugins/host-event-reactor",
]
[workspace.dependencies]
tokio = { version = "1.49.0", features = ["full", "fs"] }
sqlx = { version = "0.8.6", features = [
    "runtime-tokio",
    "tls-native-tls",
    "postgres",
    "uuid",
    "time",
] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
chrono = { version = "0.4.43", features = ["serde"] }
time = { version = "0.3.46", features = ["serde"] }
tracing = { version = "0.1.44" }
magic = "0.16.7"
color-eyre = "0.6.5"
serde-inline-default = "1.0.0"
dialoguer = { version = "0.12.0", features = ["fuzzy-select"] }
indicatif = "0.18.3"
serde_json = "1.0.138"
tokio-stream = { version = "0.1.17", features = ["io-util"] }
futures = "0.3.31"
semver = { version = "1.0.27", features = [ "serde" ] }
uuid = { version = "1.19.0", features = ["fast-rng", "v4", "serde"] }
async-trait = "0.1.89"
inventory = "0.3.21"
toml = "1.0.6"
tempfile = "3.15.0"
