[workspace]
resolver = "3"
members = [
    "bin/*",
    "crates/*",
]
exclude = [
    "examples/plugins/host-file-info",
    "examples/plugins/guest-yara-scanner",
    "examples/plugins/guest-exec-checker",
    "examples/plugins/host-event-reactor",
    "examples/plugins/host-string-extractor",
    "examples/plugins/host-result-chain",
    "examples/plugins/host-report-showcase",
    "examples/plugins/host-vbs-analyzer",
    "examples/plugins/host-yara-scanner",
    "xtask",
]
[workspace.dependencies]
tokio = { version = "1.52.3", features = ["full", "fs"] }
tokio-util = "0.7"
sqlx = { version = "0.9.0", features = [
    "runtime-tokio",
    "tls-native-tls",
    "postgres",
    "uuid",
    "time",
    "json",
] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
chrono = { version = "0.4.45", features = ["serde"] }
time = { version = "0.3.47", features = ["serde"] }
tracing = { version = "0.1.44" }
magic = "0.16.7"
color-eyre = "0.6.5"
dialoguer = { version = "0.12.0", features = ["fuzzy-select"] }
serde_json = "1.0.150"
tokio-stream = { version = "0.1.18", features = ["io-util"] }
futures = "0.3.32"
semver = { version = "1.0.28", features = [ "serde" ] }
uuid = { version = "1.23.2", features = ["fast-rng", "v4", "serde"] }
async-trait = "0.1.89"
inventory = "0.3.24"
toml = "1.0.6"
toml_edit = "0.25"
tempfile = "3.27.0"
notify = "8.2.0"
sha2 = "0.11"
hex = "0.4"
reqwest = { version = "0.13", features = ["json"] }
