[package]
name = "malbox-resources"
version = "0.1.0"
edition = "2024"

[dependencies]
malbox-machinery = { path = "../malbox-machinery" }
malbox-config = { path = "../malbox-config" }
malbox-database = { path = "../malbox-database" }
sqlx = { workspace = true }
uuid = { workspace = true }
thiserror.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["sync", "fs"] }
toml.workspace = true
sha2 = { workspace = true }
hex = { workspace = true }
serde_json = { workspace = true }
