[package]
name = "malbox-resources"
version = "0.1.0"
edition = "2024"

[dependencies]
malbox-machinery = { path = "../malbox-machinery" }
malbox-config = { path = "../malbox-config" }
malbox-plugin-transport = { path = "../malbox-plugin-transport" }
thiserror.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["sync", "fs"] }
async-trait.workspace = true
toml.workspace = true
