[package]
name = "malbox-database"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
malbox-config = { path = "../malbox-config" }
serde_json.workspace = true
thiserror.workspace = true
serde = { workspace = true }
time = { workspace = true }
chrono = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
