//! Provider imports for inventory registration.
//!
//! This module ensures that enabled provider crates are linked into the binary,
//! which allows their `inventory::submit!` calls (generated by the RegisterProvider
//! derive macro) to register providers in the global registry.
//!
//! Providers are enabled via Cargo features:
//! - `provider-libvirt` - libvirt/KVM provider
//!
//! Example usage:
//! ```bash
//! # Build with specific providers
//! cargo build -p malbox-daemon --features "provider-libvirt,provider-vmware"
//!
//! # Build with no providers (for testing)
//! cargo build -p malbox-daemon --no-default-features
//! ```

#![allow(unused_imports)]

// Link provider crates based on enabled features
// The underscore import pattern ensures the crate is linked even though
// we don't directly use any of its public items

#[cfg(feature = "provider-libvirt")]
use malbox_provider_libvirt as _;

// Uncomment as providers are implemented:
// #[cfg(feature = "provider-vmware")]
// use malbox_provider_vmware as _;

// #[cfg(feature = "provider-virtualbox")]
// use malbox_provider_virtualbox as _;
