create table samples (
    id         integer generated by default as identity primary key,
    file_size  integer not null,
    file_type  varchar not null,
    md5        varchar not null,
    crc32      varchar not null,
    sha1       varchar not null,
    sha256     varchar not null,
    sha512     varchar not null,
    ssdeep     varchar not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index hash_index on samples using btree (md5, crc32, sha1, sha256, sha512);

select trigger_updated_on('samples');
