CREATE TABLE "samples" (
    id integer generated by default as identity,
    file_size integer NOT NULL,
    file_type varchar NOT NULL,
    md5 varchar NOT NULL,
    crc32 varchar NOT NULL,
    sha1 varchar NOT NULL,
    sha256 varchar NOT NULL,
    sha512 varchar NOT NULL,
    ssdeep varchar NOT NULL,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX hash_index ON samples USING btree (md5, crc32, sha1, sha256, sha512);

SELECT trigger_updated_on('"samples"');
