CREATE TABLE "machines" (
    id integer generated by default as identity,
    name varchar(255) NOT NULL,
    label varchar(255) NOT NULL,
    arch machine_arch NOT NULL,
    platform machine_platform NOT NULL,
    ip varchar(255) NOT NULL,
    interface varchar(255),
    tags varchar[],
    snapshot varchar,
    locked boolean NOT NULL,
    locked_changed_on timestamp without time zone,
    status varchar(255),
    status_changed_on timestamp without time zone,
    reserved boolean NOT NULL DEFAULT false,
    PRIMARY KEY (id)
);

SELECT trigger_updated_on('"machines"');
