CREATE TYPE machine_status AS ENUM (
    'creating',
    'provisioning',
    'ready',
    'assigned',
    'reverting',
    'deleting',
    'failed'
);

CREATE TABLE "machines" (
    id              integer generated by default as identity,
    name            varchar(255) UNIQUE NOT NULL,
    label           varchar(255),
    arch            machine_arch NOT NULL,
    platform        machine_platform NOT NULL,
    ip              varchar(255),
    tags            varchar[],
    status          machine_status NOT NULL DEFAULT 'creating',
    image_id        UUID,
    provider        VARCHAR,
    provider_id     VARCHAR,
    last_seen       TIMESTAMPTZ,
    current_task_id INTEGER,
    error_message   TEXT,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (id)
);

SELECT trigger_updated_on('"machines"');
