create table machines (
    id                   integer generated by default as identity primary key,
    name                 varchar(255) unique not null,
    label                varchar(255),
    arch                 machine_arch not null,
    platform             machine_platform not null,
    ip                   varchar(255),
    tags                 varchar[],
    status               machine_status not null default 'creating',
    image_id             uuid references images(id),
    provider             varchar,
    provider_id          varchar,
    last_seen            timestamptz,
    current_task_id      integer,
    error_message        text,
    cpus                 integer,
    memory_mb            integer,
    disk_size_mb         bigint,
    image_name           varchar(255),
    provider_config_hash varchar(64),
    created_at           timestamptz not null default now(),
    updated_at           timestamptz not null default now()
);

select trigger_updated_on('machines');

create table machine_snapshots (
    id                   uuid primary key default uuid_generate_v1mc(),
    machine_id           integer not null references machines(id) on delete cascade,
    name                 varchar not null,
    provider_snapshot_id varchar not null,
    description          text,
    tags                 varchar[],
    guest_plugins        jsonb default '[]',
    is_active            boolean not null default false,
    created_at           timestamptz not null default now(),
    updated_at           timestamptz not null default now(),
    unique(machine_id, name)
);

select trigger_updated_on('machine_snapshots');

create table provision_runs (
    id            uuid primary key default uuid_generate_v1mc(),
    machine_id    integer not null references machines(id) on delete cascade,
    provisioner   varchar not null,
    status        provision_run_status not null default 'running',
    config        jsonb,
    output        jsonb,
    error_message text,
    snapshot_id   uuid references machine_snapshots(id) on delete set null,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now()
);

select trigger_updated_on('provision_runs');
