CREATE TABLE "tasks" (
    id integer generated by default as identity,
    target varchar NOT NULL,
    plugins varchar[] NOT NULL,
    profile varchar,
    timeout bigint DEFAULT 0 NOT NULL,
    priority bigint DEFAULT 1 NOT NULL,
    machine_id integer,
    machine_memory bigint,
    machine_cpus integer,
    platform machine_platform NOT NULL,
    enforce_timeout boolean DEFAULT true NOT NULL,
    created_on timestamp without time zone NOT NULL,
    started_on timestamp without time zone,
    completed_on timestamp without time zone,
    updated_on timestamp without time zone, -- for debugging purposes
    status task_state DEFAULT 'pending'::task_state NOT NULL,
    sample_id bigint,
    owner varchar,
    tags varchar[],
    PRIMARY KEY (id),
    FOREIGN KEY (sample_id) REFERENCES samples(id),
    FOREIGN KEY (machine_id) REFERENCES machines(id)
);

SELECT trigger_updated_on('"tasks"');
