create table tasks (
    id              integer generated by default as identity primary key,
    target          varchar not null,
    plugins         varchar[] not null,
    profile         varchar,
    timeout         bigint not null default 0,
    priority        bigint not null default 1,
    machine_id      integer references machines(id),
    machine_memory  bigint,
    machine_cpus    integer,
    platform        machine_platform,
    enforce_timeout boolean not null default true,
    created_on      timestamp without time zone not null,
    started_on      timestamp without time zone,
    completed_on    timestamp without time zone,
    updated_at      timestamp without time zone,
    status          task_state not null default 'pending',
    sample_id       bigint references samples(id),
    snapshot_id     uuid references machine_snapshots(id) on delete set null,
    owner           varchar,
    tags            varchar[]
);

select trigger_updated_on('tasks');

-- circular dependency: machines.current_task_id references tasks
alter table machines
    add constraint machines_current_task_id_fkey
    foreign key (current_task_id) references tasks(id);

create table task_results (
    id          serial primary key,
    task_id     integer not null references tasks(id),
    plugin_name text not null,
    result_name text not null,
    format      result_format not null,
    role        task_result_role not null default 'artifact',
    size_bytes  bigint not null,
    file_path   text not null,
    created_on  timestamptz not null default now()
);

create index idx_task_results_task_id on task_results(task_id);
create index idx_task_results_task_role on task_results(task_id, role);
