name: devenv - rust build and test

on:
  push:
    branches: ["main", "dev*"]
    paths:
      - 'back-end/**'
      - '.github/workflows/devenv-rust.yml'
  pull_request:
    branches: ["main", "dev*"]
    paths:
      - 'back-end/**'
      - '.github/workflows/devenv-rust.yml'

defaults:
  run:
    working-directory: back-end

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v16
      with:
        name: devenv

    - name: Install devenv
      run: nix profile install nixpkgs#devenv
      working-directory: .

    - name: Run rustfmt
      run: devenv shell -- cargo fmt --all -- --check

    # - name: Run linter
    #   run: devenv shell -- cargo clippy --all-targets --all -- -D warnings

    - name: Build project
      run: SQLX_OFFLINE=true devenv shell -- cargo build --verbose

    - name: Tests
      run: SQLX_OFFLINE=true devenv shell -- cargo nextest run --all --no-tests pass

    - name: Doctests
      run: SQLX_OFFLINE=true devenv shell -- cargo test --doc

    - name: Generate documentation
      run: SQLX_OFFLINE=true devenv shell -- cargo doc --no-deps --document-private-items
