name: devenv - Rust build and test

on:
  push:
    branches: ["main", "dev*"]
    paths:
      - 'back-end/**'
      - '.github/workflows/devenv-rust.yml'
  pull_request:
    branches: ["main", "dev*"]
    paths:
      - 'back-end/**'
      - '.github/workflows/devenv-rust.yml'

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v17
      with:
        name: devenv

    - name: Install devenv
      run: nix profile install nixpkgs#devenv

    - name: Check formatting
      run: devenv shell -- cargo fmt --manifest-path back-end/Cargo.toml --all -- --check

    # - name: Run linter
    #   run: devenv shell -- cargo clippy --manifest-path back-end/Cargo.toml --all-targets --all -- -D warnings

    - name: Build project
      run: SQLX_OFFLINE=true devenv shell -- cargo build --manifest-path back-end/Cargo.toml --verbose

    - name: Run tests
      run: SQLX_OFFLINE=true devenv shell -- cargo nextest run --manifest-path back-end/Cargo.toml --all --no-tests pass

    - name: Run doctests
      run: SQLX_OFFLINE=true devenv shell -- cargo test --manifest-path back-end/Cargo.toml --doc

    - name: Generate documentation
      run: SQLX_OFFLINE=true devenv shell -- cargo doc --manifest-path back-end/Cargo.toml --no-deps --document-private-items

    - name: Cross-compile Rust SDK (Windows)
      run: >
        SQLX_OFFLINE=true devenv shell --
        cargo build --manifest-path back-end/Cargo.toml
        -p malbox-plugin-sdk
        --target x86_64-pc-windows-gnu
        --no-default-features --features guest
