name: devenv - Rust cross-compile

on:
  push:
    branches: ["main", "dev*"]
    paths:
      - 'back-end/crates/malbox-plugin-sdk/**'
      - 'back-end/crates/malbox-plugin-transport/**'
      - '.github/workflows/devenv-rust-cross.yml'
  pull_request:
    branches: ["main", "dev*"]
    paths:
      - 'back-end/crates/malbox-plugin-sdk/**'
      - 'back-end/crates/malbox-plugin-transport/**'
      - '.github/workflows/devenv-rust-cross.yml'

jobs:
  cross-compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v17
      with:
        name: devenv

    - name: Install devenv
      run: nix profile install nixpkgs#devenv

    - name: Cross-compile Rust SDK (Windows)
      run: >
        SQLX_OFFLINE=true devenv shell --
        cargo build --manifest-path back-end/Cargo.toml
        -p malbox-plugin-sdk
        --target x86_64-pc-windows-gnu
        --no-default-features --features guest
